# Generated by Django 4.2.5 on 2023-09-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('industry', models.CharField(default='', max_length=100)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('year_founded', models.PositiveIntegerField(
                    blank=True, default=None, null=True)),
                ('number_of_employees', models.PositiveIntegerField(
                    blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('lead_source', models.CharField(blank=True,
                 default=None, max_length=100, null=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('expected_close_date', models.DateField(
                    blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True,
                 default=None, max_length=100, null=True)),
                ('start_date', models.DateField(
                    blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_amount', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(
                    blank=True, default='', max_length=50, null=True)),
                ('order_description', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='website.companies')),
                ('manager', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='website.managers')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('social_media', models.URLField(
                    blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(
                    blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='website.companies')),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='website.managers'),
        ),
    ]
