# Generated by Django 4.2.5 on 2023-09-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
    ]
