# Generated by Django 4.2.5 on 2023-09-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_department_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
