# Generated by Django 4.2.5 on 2023-09-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_department_jobposition_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobposition'),
        ),
    ]
