# Generated by Django 4.2.5 on 2023-09-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_title_contacts_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
