# Generated by Django 4.2.5 on 2023-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Company',
            field=models.CharField(default='time', max_length=100),
            preserve_default=False,
        ),
    ]
