# Generated by Django 4.2.5 on 2023-09-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_department_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='social_media',
        ),
    ]
