# Generated by Django 4.2.5 on 2023-09-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_orders_product_alter_orders_quantity_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='quantity_ordered',
            new_name='order_amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
