# Generated by Django 4.2.5 on 2023-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_quantity_ordered_orders_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_date',
            field=models.DateField(verbose_name='Shipping Date'),
        ),
    ]
