# Generated by Django 4.2.5 on 2023-09-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
