# Generated by Django 4.2.5 on 2023-09-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_orders_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.managers'),
        ),
    ]
