# Generated by Django 4.2.5 on 2023-09-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_orders_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
