# Generated by Django 4.2.5 on 2023-09-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_product_minimum_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=None),
        ),
    ]
